// datasheet page no. 28 - 9. COMMAND TABLE

#pragma once

// base commands
#define PICO_SSD1306_SET_CONTRAST_CONTROL_REG _u(0x81)
#define PICO_SSD1306_SET_CONTRAST_RESET _u(0xFF)
#define PICO_SSD1306_BASE_ENTIRE_DISPLAY_ON _u(0xA4)
#define PICO_SSD1306_BASE_SET_NORMAL_DISPLAY _u(0xA6)
#define PICO_SSD1306_BASE_DISPLAY_ON _u(0xAF)
#define PICO_SSD1306_BASE_DISPLAY_OFF _u(0xAE)

// scrolling commands - not supported
#define PICO_SSD1306_SCROLLING_DEACTIVATE_SCROLL _u(0x2E)

// addressing setting commands
#define PICO_SSD1306_SET_MEMORY_ADDRESSING_MODE_REG _u(0x20)
#define PICO_SSD1306_SET_MEMORY_HORIZONTAL_ADDRESSING_MODE _u(0x00)
#define PICO_SSD1306_SET_MEMORY_VERTICAL_ADDRESSING_MODE _u(0xA1)
#define PICO_SSD1306_SET_MEMORY_PAGE_ADDRESSING_MODE _u(0xA2)

#define PICO_SSD1306_SET_COLUMN_ADDRESS_REG _u(0x21)
#define PICO_SSD1306_SET_PAGE_ADDRESS_REG _u(0x22)
#define PICO_SSD1306_SET_PAGE_START_ADDRESS _u(0xB0)

// hardware configuration
#define PICO_SSD1306_SET_DISPLAY_START_LINE _u(0x40)
#define PICO_SSD1306_SET_SEGMENT_REMAP _u(0xA0)
#define PICO_SSD1306_SET_SEGMENT_REMAP_INV _u(0xA1)
#define PICO_SSD1306_SET_MULTIPLEX_RATIO_REG _u(0xA8)
#define PICO_SSD1306_SET_MULTIPLEX_RATIO _u(0x3F)
#define PICO_SSD1306_SET_COM_OUTPUT_SCAN_DIRECTION _u(0xC0)
#define PICO_SSD1306_SET_COM_OUTPUT_SCAN_DIRECTION_INV _u(0xC8)
#define PICO_SSD1306_SET_DISPLAY_OFFSET_REG _u(0xD3)
#define PICO_SSD1306_SET_DISPLAY_OFFSET _u(0x00)
#define PICO_SSD1306_SET_COM_PINS_HARDWARE_CONFIGURATION_REG _u(0xDA)
#define PICO_SSD1306_SET_COM_PINS_HARDWARE_CONFIGURATION _u(0x12)

// timing & driving scheme setting
#define PICO_SSD1306_SET_DISPLAY_CLOCK_DIVIDE_RATIO_REG _u(0xD5)
#define PICO_SSD1306_SET_DISPLAY_CLOCK_DIVIDE_RATIO _u(0x80)
#define PICO_SSD1306_SET_PRECHARGE_PERIOD_REG _u(0xD9)
#define PICO_SSD1306_SET_PRECHARGE_PERIOD _u(0xF1)
#define PICO_SSD1306_SET_VCOMH_DESELECT_LEVEL_REG _u(0xD8)
#define PICO_SSD1306_SET_VCOMH_DESELECT_LEVEL_TOP _u(0x30)

// charge bump setting
#define PICO_SSD1306_SET_CHARGE_PUMP_SETTING_REG _u(0x8D)
#define PICO_SSD1306_SET_CHARGE_PUMP_SETTING _u(0x14)
